### ISSUE TITLE
future compatibility problem in dependencies

### ISSUE THREAD

**Issue by hdhoang** [azizunsal/waveformrs#1]
Hi, due to rust-lang/rust#49799, one of your dependencies will no longer build. From looking at your Cargo.lock, we recommend you
update  image/imageproc (newer versions no longer use a broken nalgebra).
Thanks for your attention!

**Comment by azizunsal** [comment]
Thank you @hdhoang. I've fixed it with 032beeea7ea2b1f88f7937fb713f4d06c06ac5bc
